# Generated by Django 4.1.2 on 2022-10-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum', models.IntegerField()),
                ('ename', models.CharField(max_length=128)),
                ('esal', models.FloatField()),
                ('ecity', models.CharField(max_length=128)),
            ],
        ),
    ]
